language: bash
install: true
services:
  - docker

env:
  global:
    - COMPOSE_VERSION=1.16.1

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f tests/docker-compose.yml build

script:
  - docker-compose -f tests/docker-compose.yml up -d
  - docker-compose -f tests/docker-compose.yml run wait
  - docker-compose -f tests/docker-compose.yml run test nosetests --with-xcoverage --cover-package=viewer --rednose -v

after_success:
  - docker-compose -f tests/docker-compose.yml run test python-codacy-coverage -r coverage.xml

notifications:
  email: false
