version: '3'
services:
  viewer:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/viewer"
  datastore-emulator:
    build:
       context: .
       dockerfile: docker/Docker.datastore
    environment:
       - CLOUDSDK_CORE_PROJECT=test
