version: '3'
services:
  viewer:
    build:
      context: .
    command:
      - "python"
      - "/app/app.py"
    environment:
      - DATASTORE_EMULATOR_HOST=datastore-emulator:8000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/test.json
    ports:
      - "5000:5000"
    volumes:
      - ".:/app/"
    depends_on:
      -  datastore-emulator

  datastore-emulator:
    build:
       context: .
       dockerfile: docker/Docker.datastore
    environment:
       - CLOUDSDK_CORE_PROJECT=test
